### ISSUE TITLE
Rubygems release version is confusing

### ISSUE THREAD

**Issue by psharpNumerex** [thebestday/delayed-web#11]
Using this gem from the github repo with 4.2 and it works great, but I'm a bit confused by the rubygems version:

https://rubygems.org/gems/delayed-web

That indicates 0.2.0, while this repo is 0.0.1?

**Comment by tatey** [comment]
Ah, none of the maintainers for this project are responsible for publishing the gem. Will try to get in contact with the owner and see if we can align our goals. In the mean time you can use the gem directly from GitHub by adding `gem 'delayed-web', github: 'thebestday/delayed-web' to your Gemfile.

**Comment by tatey** [comment]
The repo and rubygems are now in sync. Both are at 0.3.0. Figured it was worth bumping the version given it hasn't been done in a while.

Thanks very much to @pcragone who has been maintaining the rubygem originally and kindly added me as co-owner.
