### ISSUE TITLE
Rails 5.x compatibility

### ISSUE THREAD

**Issue by cseelus** [thebestday/delayed-web#13]
I am getting a bundle conflict due to delayed-web's rails (< 4.3.0, >= 3.2.13) requirement on Rails 5.0.0.rc1

**Comment by tatey** [comment]
I don't have any current Rails 5 projects that are using Delayed::Job. Would you mind forking this repo, updating the gem requirement, and seeing if it works? I'll gladly accept a PR 😉

**Comment by cseelus** [comment]
Works as [expected](https://github.com/thebestday/delayed-web/pull/14).

**Comment by tatey** [comment]
Fixed by #14.

**Comment by tatey** [comment]
I've deployed a new version of the gem to rubygems.org.

https://rubygems.org/gems/delayed-web/versions/0.4.0

**Comment by cseelus** [comment]
Awesome, that was fast!

**Comment by cseelus** [comment]
Now the same problem with Rails 5.0.0.1

Would it be ok if the dependency for Rails would be specified just as `'>= 3.2.13'` to avoid similar issues in the future? I could create a PR.
