### ISSUE TITLE
delayed-web not working with rails 5

### ISSUE THREAD

**Issue by ElayanHamamrah** [thebestday/delayed-web#15]
Hello, 
just tried to work with delayed-web, and it's not installing when running "bundle install". 
I'm working on rails 5

**Comment by coop** [comment]
@ElayanHamamrah send a PR that bumps the rails dep and I'll merge.

**Comment by ElayanHamamrah** [comment]
What did you mean exactly !!

**Comment by cseelus** [comment]
Now that https://github.com/thebestday/delayed-web/pull/16 is merged, could you guys push it to Rubygems as well?

**Comment by tatey** [comment]
Done https://rubygems.org/gems/delayed-web/versions/0.4.1

**Comment by tatey** [comment]
I've also updated the specs to run against Rails 5 in 7645bd3f76216b5fcaf1ea426841888afb53e197
