### ISSUE TITLE
Rails 4.2 support

### ISSUE THREAD

**Issue by scottrobertson** [thebestday/delayed-web#7]
Much work to get this working?

**Comment by tatey** [comment]
Probably as simple as incrementing the version number [lib/delayed/web/version.rb](https://github.com/thebestday/delayed-web/blob/master/lib/delayed/web/version.rb). Would you mind having a crack and trying it out? I don't have any active projects on 4.2 where I'm using Delayed::Job.

**Comment by scottrobertson** [comment]
Just did :) all working perfectly fine. Shall PR it now.
